services:
  - type: web
    name: person-detection-app
    runtime: python3
    pythonVersion: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_person:app
    envVars:
      - key: PORT
        value: 10000